In [12]:
import joblib
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

In [2]:
# data_row = '0.0,0.0,0.13793103448275862,0.30344827586206896,0.31724137931034485,0.5655172413793104,0.47586206896551725,0.7793103448275862,0.503448275862069,1.0,0.6827586206896552,0.2620689655172414,0.8620689655172413,0.31724137931034485,0.6206896551724138,0.2896551724137931,0.5862068965517241,0.2689655172413793,0.696551724137931,0.07586206896551724,0.8758620689655172,0.13793103448275862,0.5862068965517241,0.1310344827586207,0.5793103448275863,0.0896551724137931,0.6827586206896552,-0.1103448275862069,0.8896551724137931,-0.06896551724137931,0.6275862068965518,-0.041379310344827586,0.6,-0.08275862068965517,0.6551724137931034,-0.32413793103448274,0.8068965517241379,-0.2689655172413793,0.6344827586206897,-0.2206896551724138,0.5793103448275863,-0.2413793103448276'

In [3]:
rf_model = joblib.load('keypoint_classifier_rf.joblib')

In [7]:

dataset = r'keypoint_logs.csv'

X_dataset = np.loadtxt(dataset, delimiter=',', dtype='float32', usecols=list(range(1, 43)))
y_dataset = np.loadtxt(dataset, delimiter=',', dtype='int32', usecols=(0))
X_train, X_test, y_train, y_test = train_test_split(X_dataset, y_dataset, train_size=0.75, random_state=42)

In [8]:
y_pred = rf_model.predict(X_test)


In [10]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')  # Use appropriate average parameter
recall = recall_score(y_test, y_pred, average='weighted')  # Use appropriate average parameter
f1 = f1_score(y_test, y_pred, average='weighted') 
conf_matrix = confusion_matrix(y_test, y_pred)


In [11]:
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.996661101836394
Precision: 0.9966971980327574
Recall: 0.996661101836394
F1 Score: 0.9966618276838207
Confusion Matrix:
 [[398   4   0   0   0   0   0   0]
 [  0 366   0   0   0   0   0   0]
 [  0   0  95   0   0   0   0   0]
 [  0   0   0  60   0   0   0   0]
 [  0   0   0   0  67   0   0   0]
 [  0   0   0   0   0  78   0   0]
 [  0   0   0   0   0   0  66   0]
 [  0   0   0   0   0   0   0  64]]


In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       402
           1       0.99      1.00      0.99       366
           2       1.00      1.00      1.00        95
           3       1.00      1.00      1.00        60
           4       1.00      1.00      1.00        67
           5       1.00      1.00      1.00        78
           6       1.00      1.00      1.00        66
           7       1.00      1.00      1.00        64

    accuracy                           1.00      1198
   macro avg       1.00      1.00      1.00      1198
weighted avg       1.00      1.00      1.00      1198

